### PR TITLE
Moved models to a new folder, 1x2 Prop Triangle

### PR DESCRIPTION
**Pull request by DatCaptainHorse**
Moving models into their separate folders, by Creator and Set would make
them organized.

1x2 size Triangle Prop, may be bit off.

### CODE REVIEW

**Comment by Yuri6037** [comment]
Well for the moment I'll rest with the current organisation. The problem with your pull request is your file names, please use the file naming style I use here.
Those file names will be reproduced in game by the spawn menu in the future.

**Comment by DatCaptainHorse** [comment]
So, how do I translate.. for example: Prop_Square_1x1 to Yuri name format?

**Comment by Yuri6037** [comment]
Well the names you're using should use _ instead of space or -.

After, I'll wrap all inside a folder containing your name. But you have to know that currently I can't do much, I'm still in weapon system so you'll need to wait until weapon system is done. I'm indeed trying to add a physic gun. And for the moment it's realy complicated because all parenting methods of unreal engine are broken and I have no control over PhysX ! Unreal don't even give an access to toggle gravity or even scale gravity.

**Comment by Yuri6037** [comment]
Content stuff is in wait as I plan to re-organize again all the content. And the StarterContent will probably be removed after I will have done some usefull classes/particles systems/other content

**Pull request closed without merging**
